In [1]:
import numpy as np

In [2]:
import numpy as np

# Check the version
print(np.__version__)

1.26.0


In [3]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])


In [4]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [6]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), 
                                    columns=['a', 'b', 'c'])
df

a  b  c
0  6  4  7
1  6  6  4
2  8  4  6
3  6  5  9
4  5  9  3

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Array

- np.array()
- np.ones()
- np.zeros()
- np.random.rand(5, 3)
- np.random.randint(10, size=5)
- np.random.seed() - pseudo random numbers
- Searching the documentation example (finding np.unique() and using it)

In [13]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [14]:
simple_array = np.array((1, 2, 3))
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

In [15]:
# Create an array of ones
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
# Create an array of zeros
zeros = np.zeros((4, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of values
# start, stop, step
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[3, 2, 6],
       [3, 3, 2],
       [8, 5, 2],
       [2, 7, 2],
       [1, 4, 5]])

In [21]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.10408024, 0.4516261 , 0.78429821],
       [0.62487246, 0.99920556, 0.80267584],
       [0.58774648, 0.55877616, 0.42063552],
       [0.57858801, 0.74219967, 0.67270113],
       [0.67007552, 0.41875031, 0.82111447]])

In [22]:
# Random 5x3 array of floats (between 0 & 1), similar to above
np.random.rand(5, 3)

array([[0.21755094, 0.67449666, 0.80333522],
       [0.7960091 , 0.13774332, 0.57350681],
       [0.27716337, 0.63322501, 0.27909644],
       [0.73290639, 0.94226075, 0.42459457],
       [0.89022705, 0.68773485, 0.1966997 ]])

In [23]:
# Set random seed to 0
np.random.seed(0)
# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [24]:
np.random.seed(0)
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [25]:
np.random.seed(2)
np.random.randint(10, size=(5, 3))

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

In [26]:
np.random.seed(2)
np.random.randint(10, size=(5, 3))

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

In [27]:
np.random.seed(0)
np.random.randint(10, size=(5, 3)), np.random.randint(10, size=(5, 3))

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

- Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with np.random.seed() set to 0 as well.

- Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

- For example, say you wanted to split your data randomly into training and test sets.

    Every time you randomly split, you might get different rows in each set.
    
    If you shared your work with someone else, they'd get different rows in each set too.

- Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.

In [28]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0]],

        [[0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2]],

        [[0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1]]],


       [[[5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7]],

        [[2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6]],

        [[0, 6, 3, 3, 8],
         [8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0]]]])

In [29]:
a4[ :1 , : , : , :2]

array([[[[2, 3],
         [3, 3],
         [9, 9],
         [3, 2]],

        [[0, 4],
         [8, 4],
         [8, 1],
         [9, 3]],

        [[0, 3],
         [4, 6],
         [4, 4],
         [7, 5]]]])

In [32]:
aa1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
aa1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
aa2 = np.array([
    [7, 1, 4],
    [1, 3, 2]
])
aa2

array([[7, 1, 4],
       [1, 3, 2]])

In [36]:
aa1 * aa2

array([[ 7,  2, 12],
       [ 4, 15, 12]])

In [40]:
aa1 / aa2

array([[0.14285714, 2.        , 0.75      ],
       [4.        , 1.66666667, 3.        ]])

In [41]:
aa1 // aa2

array([[0, 2, 0],
       [4, 1, 3]])

In [42]:
aa1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [43]:
np.square(aa1)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [44]:
aa1 % aa2

array([[1, 0, 3],
       [0, 2, 0]])

In [45]:
aa1 % 4

array([[1, 2, 3],
       [0, 1, 2]])

In [46]:
np.exp(aa1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [47]:
np.log(aa1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

# Converting images to numpy array
<img src="images/numpy-panda.jpeg" />

In [48]:
from matplotlib.image import imread

In [49]:
panda_img_array = imread("images/numpy-panda.jpeg")
type(panda_img_array)

numpy.ndarray

In [52]:
panda_img_array.size, panda_img_array.shape, panda_img_array.ndim

(3271680, (852, 1280, 3), 3)

In [50]:
panda_img_array

array([[[14, 27, 17],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 36, 24],
        [42, 35, 25],
        [41, 34, 24]],

       [[14, 27, 17],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 36, 24],
        [42, 35, 25],
        [42, 35, 25]],

       [[13, 26, 16],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 36, 24],
        [42, 35, 25],
        [42, 35, 25]],

       ...,

       [[47, 32, 27],
        [48, 33, 28],
        [48, 33, 26],
        ...,
        [ 6,  6,  8],
        [ 6,  6,  8],
        [ 6,  6,  8]],

       [[39, 24, 17],
        [40, 25, 18],
        [42, 27, 20],
        ...,
        [ 6,  6,  8],
        [ 6,  6,  8],
        [ 6,  6,  8]],

       [[32, 17, 10],
        [33, 18, 11],
        [36, 21, 14],
        ...,
        [ 6,  6,  8],
        [ 6,  6,  8],
        [ 6,  6,  8]]], dtype=uint8)